// Package main is the Dagger CI/release module for siyuan-knowledge-sync.
//
// It cross-compiles the CLI for the supported release targets inside a
// reproducible golang container and packages a checksummed dist directory.
// Supported targets: linux/amd64, linux/arm64, darwin/amd64, darwin/arm64
// (Windows is intentionally not built).
//
// Lives under .dagger/ so Go's `./...` package matching ignores it and the
// main module's build/test/e2e gates are unaffected. The internal/dagger SDK
// is generated by `dagger develop` / `dagger call` and is not committed.
package main

import (
	"context"
	"fmt"

	"dagger/ci/internal/dagger"
)

// Ci groups the build/test/release pipeline for siyuan-knowledge-sync.
type Ci struct{}

// goImage is the toolchain image; matches the go directive in go.mod (go 1.26.x).
const goImage = "golang:1.26"

// releaseTargets is the supported OS/ARCH matrix. No Windows by design.
var releaseTargets = []struct{ Goos, Goarch string }{
	{"linux", "amd64"},
	{"linux", "arm64"}, // aarch64
	{"darwin", "amd64"},
	{"darwin", "arm64"}, // Apple silicon
}

// goBase returns a golang container with module/build caches and the source mounted.
func (m *Ci) goBase(source *dagger.Directory) *dagger.Container {
	return dag.Container().
		From(goImage).
		WithMountedCache("/go/pkg/mod", dag.CacheVolume("sks-go-mod")).
		WithMountedCache("/root/.cache/go-build", dag.CacheVolume("sks-go-build")).
		WithMountedDirectory("/src", source).
		WithWorkdir("/src")
}

// Test runs vet plus the unit/integration suite. The Docker-based e2e package
// is intentionally excluded from containerized CI (it needs a SiYuan container).
func (m *Ci) Test(
	ctx context.Context,
	// +defaultPath="/"
	source *dagger.Directory,
) (string, error) {
	return m.goBase(source).
		WithExec([]string{"go", "vet", "./internal/...", "./cmd/..."}).
		WithExec([]string{"go", "test", "./internal/...", "./cmd/..."}).
		Stdout(ctx)
}

// Build cross-compiles the CLI for every release target and returns a
// directory containing one static binary per target.
func (m *Ci) Build(
	// +defaultPath="/"
	source *dagger.Directory,
	// +optional
	// +default="dev"
	version string,
) *dagger.Directory {
	out := dag.Directory()
	for _, t := range releaseTargets {
		name := fmt.Sprintf("siyuan-knowledge-sync_%s_%s_%s", version, t.Goos, t.Goarch)
		bin := m.goBase(source).
			WithEnvVariable("CGO_ENABLED", "0").
			WithEnvVariable("GOOS", t.Goos).
			WithEnvVariable("GOARCH", t.Goarch).
			WithExec([]string{
				"go", "build", "-trimpath", "-ldflags", "-s -w",
				"-o", "/out/" + name, "./cmd/siyuan-knowledge-sync",
			}).
			File("/out/" + name)
		out = out.WithFile(name, bin)
	}
	return out
}

// Release builds all targets and appends a SHA256SUMS manifest. Export with:
//
//	dagger call release --version=v1.2.3 export --path=./dist
func (m *Ci) Release(
	// +defaultPath="/"
	source *dagger.Directory,
	// +optional
	// +default="dev"
	version string,
) *dagger.Directory {
	dist := m.Build(source, version)
	sums := dag.Container().
		From("alpine:3.20").
		WithMountedDirectory("/dist", dist).
		WithWorkdir("/dist").
		WithExec([]string{"sh", "-c", "sha256sum siyuan-knowledge-sync_* > SHA256SUMS"}).
		File("/dist/SHA256SUMS")
	return dist.WithFile("SHA256SUMS", sums)
}
